# Generated by Django 4.1.4 on 2022-12-12 06:10

import app.utils.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default=app.utils.generate.nanoid_generate, max_length=255, unique=True, verbose_name='code'),
        ),
    ]
