# Generated by Django 4.1.4 on 2022-12-11 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_store_campaign_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='plan',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='assigned_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='campaign',
            field=models.ManyToManyField(related_name='stores', to='app.campaign'),
        ),
    ]
