# Generated by Django 4.1 on 2022-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_country_remove_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
