# Generated by Django 4.1.4 on 2022-12-11 18:12

import app.utils.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, default=app.utils.generate.order_id_generate, max_length=255, unique=True, verbose_name='code'),
        ),
    ]
