# Generated by Django 4.1.4 on 2022-12-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_by',
            new_name='upload_by',
        ),
    ]
