# Generated by Django 4.1.4 on 2022-12-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_form_plan_status_alter_plan_assignee_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='app.form'),
        ),
    ]
