# Generated by Django 4.1.4 on 2022-12-12 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_created_by_file_upload_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
