# Generated by Django 4.1.4 on 2022-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_formfield_field_alter_formfield_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='index',
            field=models.IntegerField(default=0, verbose_name='index'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
    ]
