# Generated by Django 4.1.4 on 2022-12-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_formfield_default_value_formfield_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('number', 'Number')], default='text', max_length=255, verbose_name='field'),
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='index')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='app.formfield')),
            ],
            options={
                'verbose_name': 'field option',
                'verbose_name_plural': 'field options',
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='app.fieldoption'),
        ),
    ]
