# Generated by Django 4.1.4 on 2022-12-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_formfield_option_formfield_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='created_by',
        ),
    ]
