# Generated by Django 4.1.4 on 2022-12-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_formfield_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ('-index',), 'verbose_name': 'field option', 'verbose_name_plural': 'field options'},
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_select',
            field=models.IntegerField(default=0, verbose_name='max select'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_select',
            field=models.IntegerField(default=0, verbose_name='min select'),
        ),
    ]
