# Generated by Django 4.1.4 on 2022-12-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_fieldoption_options_formfield_max_select_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='option',
        ),
        migrations.DeleteModel(
            name='FieldOption',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
