# Generated by Django 4.1.4 on 2022-12-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_form_created_by_remove_formfield_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='plans', to='app.store'),
        ),
    ]
