# Generated by Django 4.1.4 on 2022-12-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
