# Generated by Django 4.1.4 on 2022-12-11 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='photo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='country')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='zip code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('project', models.ManyToManyField(blank=True, related_name='profiles', to='app.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
