# Generated by Django 4.1.4 on 2022-12-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_address_full_address_alter_address_address'),
        ('app', '0017_alter_employee_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='place.address'),
        ),
    ]
