# Generated by Django 4.1.4 on 2022-12-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_store_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='place',
        ),
    ]
