# Generated by Django 4.1 on 2022-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='form_field',
        ),
        migrations.AddField(
            model_name='formfield',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='form_fields', to='form.option'),
        ),
    ]
