# Generated by Django 4.1.4 on 2022-12-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('-created_at',), 'verbose_name': 'field', 'verbose_name_plural': 'fields'},
        ),
    ]
