# Generated by Django 4.1.4 on 2022-12-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ('-created_at',), 'verbose_name': 'form field', 'verbose_name_plural': 'form fields'},
        ),
    ]
