# Generated by Django 4.1.4 on 2022-12-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_field_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldoption',
            old_name='form_field',
            new_name='field',
        ),
    ]
