# Generated by Django 4.1.4 on 2022-12-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_formfield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'verbose_name': 'form field', 'verbose_name_plural': 'form fields'},
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='max_select',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='min_select',
        ),
    ]
