# Generated by Django 4.1 on 2023-01-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_option_form_field_formfield_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='FieldOption',
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'verbose_name': 'field option', 'verbose_name_plural': 'field options'},
        ),
    ]
