# Generated by Django 4.1.4 on 2022-12-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_formfield_options_remove_formfield_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='type',
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='form.fieldtype'),
        ),
    ]
