# Generated by Django 4.1.4 on 2022-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_form_field_fieldoption_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('number', 'Number')], default='text', max_length=255, verbose_name='type'),
        ),
    ]
