# Generated by Django 4.1.4 on 2022-12-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_formfield_type_formfield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='regex',
        ),
    ]
