# Generated by Django 4.1.4 on 2022-12-12 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_remove_formfield_description_remove_formfield_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='index',
            field=models.IntegerField(default=0, verbose_name='index'),
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='value'),
            preserve_default=False,
        ),
    ]
