# Generated by Django 4.1.4 on 2022-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_option_index_option_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'option', 'verbose_name_plural': 'options'},
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='field_type_icons/%Y/%m/%d', verbose_name='icon'),
        ),
    ]
