name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Django Docker Build
        run: |
          ls -a
          cp ./.env.example ./.env
          docker compose build
          
      - name: Django Deploy
        run: |
          docker compose up -d

