name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Django Docker Build
        run: |
          ls -a
          cp ./.env.example ./.env
          docker compose build  
        
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: docker compose up -d
        
  migrate:
    runs-on: self-hosted
    steps:
      - name: Migrate
        run: echo "test"


