name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  activation_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Django Docker Build
        run: |
          ls -a
          cp ./.env.example ./.env
          docker compose build  
      
      - name: Django Docker Deploy
        run: |
          docker compose up -d
