name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Django Docker Build
        run: |
          ls -a
          cp ./.env.example ./.env
          docker compose build
          docker compose up
